# Generated by Django 4.2.16 on 2025-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_productscheme_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
