# Generated by Django 4.2.16 on 2025-01-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_post_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='product_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='services',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productscheme',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
