# Generated by Django 4.2.16 on 2025-01-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product_scheme',
        ),
    ]
