# Generated by Django 4.2.16 on 2025-01-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_payment_product_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productscheme'),
        ),
    ]
